// Generates only product projection types from their Go authority, not Codex wire types.
package main

import (
	"flag"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"

	"github.com/caelis-labs/caelis-bot/internal/backend/api"
)

func main() {
	check := flag.Bool("check", false, "check generated projection")
	flag.Parse()
	types := map[string]reflect.Type{}
	var ts func(reflect.Type) string
	ts = func(t reflect.Type) string {
		switch t.Kind() {
		case reflect.String:
			return "string"
		case reflect.Bool:
			return "boolean"
		case reflect.Int, reflect.Int64, reflect.Uint64:
			return "number"
		case reflect.Slice:
			return "Array<" + ts(t.Elem()) + ">"
		case reflect.Map:
			return "Record<string, " + ts(t.Elem()) + ">"
		case reflect.Struct:
			types[t.Name()] = t
			return t.Name()
		default:
			panic("unsupported contract type: " + t.String())
		}
	}
	for _, v := range []any{api.Snapshot{}, api.ChatUpdate{}, api.AttachmentStorage{}, api.Submission{}, api.Receipt{}, api.Decision{}, api.Draft{}, api.RuntimeSettings{}, api.RuntimeCheck{}, api.ExecutionSettings{}, api.ModelOption{}} {
		ts(reflect.TypeOf(v))
	}
	for previous := 0; previous != len(types); {
		previous = len(types)
		for _, t := range types {
			for i := 0; i < t.NumField(); i++ {
				ts(t.Field(i).Type)
			}
		}
	}
	keys := make([]string, 0, len(types))
	for key := range types {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var out strings.Builder
	out.WriteString("// Generated by go run ./cmd/contract-gen. Edit internal/backend/api/contract.go.\n")
	for _, key := range keys {
		t := types[key]
		fmt.Fprintf(&out, "export interface %s {\n", key)
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			fmt.Fprintf(&out, "  %s: %s;\n", strings.Split(f.Tag.Get("json"), ",")[0], ts(f.Type))
		}
		out.WriteString("}\n")
	}
	path := "frontend/src/backend/contract.ts"
	if *check {
		b, err := os.ReadFile(path)
		if err != nil || string(b) != out.String() {
			fmt.Fprintln(os.Stderr, "Backend UI types drifted; run go run ./cmd/contract-gen")
			os.Exit(1)
		}
	} else if err := os.WriteFile(path, []byte(out.String()), 0644); err != nil {
		panic(err)
	}
}
