// Generates only product projection types from their Go authority, not Codex wire types.
package main

import (
	"flag"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"

	"github.com/caelis-labs/caelis-bot/internal/backend"
	"github.com/caelis-labs/caelis-bot/internal/backend/api"
	"github.com/caelis-labs/caelis-bot/internal/notebooksync"
)

func main() {
	check := flag.Bool("check", false, "check generated projection")
	flag.Parse()
	out := generateProjection(productRoots()...)
	path := "frontend/src/backend/contract.ts"
	if *check {
		b, err := os.ReadFile(path)
		if err != nil || string(b) != out {
			fmt.Fprintln(os.Stderr, "Backend UI types drifted; run go run ./cmd/contract-gen")
			os.Exit(1)
		}
	} else if err := os.WriteFile(path, []byte(out), 0644); err != nil {
		panic(err)
	}
}

func productRoots() []any {
	return []any{api.Snapshot{}, api.ChatUpdate{}, api.AttachmentStorage{}, api.Submission{}, api.Receipt{}, api.Decision{}, api.Draft{}, api.RuntimeSettings{}, api.RuntimeCheck{}, api.RuntimeStatus{}, api.ExecutionSettings{}, api.WorkExecutionSettings{}, api.ModelOption{}, api.ProviderInfo{}, api.ExecutionOptions{}, api.SetupRequest{}, api.SetupState{}, api.SetupChoice{}, api.SetupOverview{}, api.BotInitialization{}, api.BotIntroduction{}, api.RuntimeConfiguration{}, api.RuntimeConfigurationChange{}, api.RuntimeMutationResult{}, api.RuntimeConnectionCatalog{}, api.RuntimeConnectionInput{}, api.RuntimeFlow{}, api.RuntimeFlowAction{}, api.Task{}, api.TaskStart{}, api.TaskMessage{}, api.TaskPreview{}, api.WorkTargetInfo{}, backend.WorkerNodeSetup{}, backend.ProductConnectionState{}, backend.RemoteRuntimeState{}, backend.RemoteRuntimeRequest{}, backend.RemoteConfigurationRequest{}, backend.RemoteManagementResult{}, backend.RemoteExecutionView{}, backend.RemoteExecutionRequest{}, api.NodeCatalog{}, api.NodeManagementRequest{}, api.NodeOperationReceipt{}, api.NodeRuntimeConfiguration{}, api.NodeRuntimeConnectionRef{}, api.NodeAddRequest{}, api.NodeAddResult{}, api.NodeCoordinatorSelection{}, backend.NodeRoamingRequest{}, backend.NodeRoamingState{}, backend.NodeRoamingPlan{}, backend.NodeRoamingPlanAction{}, backend.NotebookSyncSettings{}, notebooksync.State{}}
}

func generateProjection(roots ...any) string {
	types := map[string]reflect.Type{}
	var ts func(reflect.Type) string
	ts = func(t reflect.Type) string {
		switch t.Kind() {
		case reflect.String:
			return "string"
		case reflect.Bool:
			return "boolean"
		case reflect.Int, reflect.Int64, reflect.Uint64:
			return "number"
		case reflect.Pointer:
			return ts(t.Elem()) + " | null"
		case reflect.Slice:
			return "Array<" + ts(t.Elem()) + ">"
		case reflect.Map:
			return "Record<string, " + ts(t.Elem()) + ">"
		case reflect.Struct:
			types[t.Name()] = t
			return t.Name()
		default:
			panic("unsupported contract type: " + t.String())
		}
	}
	for _, v := range roots {
		ts(reflect.TypeOf(v))
	}
	for previous := 0; previous != len(types); {
		previous = len(types)
		for _, t := range types {
			for i := 0; i < t.NumField(); i++ {
				if t.Field(i).Tag.Get("json") == "-" {
					continue
				}
				ts(t.Field(i).Type)
			}
		}
	}
	keys := make([]string, 0, len(types))
	for key := range types {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var out strings.Builder
	out.WriteString("// Generated by go run ./cmd/contract-gen. Edit internal/backend/api/contract.go.\n")
	for _, key := range keys {
		t := types[key]
		fmt.Fprintf(&out, "export interface %s {\n", key)
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			if f.Tag.Get("json") == "-" {
				continue
			}
			optional := ""
			if strings.Contains(f.Tag.Get("json"), ",omitempty") {
				optional = "?"
			}
			fmt.Fprintf(&out, "  %s%s: %s;\n", strings.Split(f.Tag.Get("json"), ",")[0], optional, ts(f.Type))
		}
		out.WriteString("}\n")
	}
	return out.String()
}
