// Generated by go run ./cmd/contract-gen. Edit internal/backend/api/contract.go.
export interface Activity {
  kind: string;
  target: string;
}
export interface Approval {
  titleKey: string;
  noticeKey: string;
  taskTitle: string;
  sections: Array<ApprovalSection>;
  id: string;
  title: string;
  action: string;
  target: string;
  description: string;
  details: string;
  status: string;
  choices: Array<Choice>;
  questions: Array<Question>;
  url: string;
}
export interface ApprovalMode {
  id: string;
  name: string;
  description: string;
  dangerous: boolean;
}
export interface ApprovalSection {
  titleKey: string;
  text: string;
}
export interface Artifact {
  id: string;
  name: string;
}
export interface AttachmentStorage {
  files: number;
  bytes: number;
  eligibleFiles: number;
  eligibleBytes: number;
  canClean: boolean;
  notice: string;
}
export interface BotInitialization {
  required: boolean;
  status: string;
  message: string;
}
export interface BotIntroduction {
  name: string;
  description: string;
}
export interface Capabilities {
  execution: boolean;
  installation: boolean;
  configuration: boolean;
  configurationReceiptLookup: boolean;
}
export interface ChatUpdate {
  changed: boolean;
  snapshot: Snapshot;
}
export interface Choice {
  id: string;
  label: string;
  labelKey: string;
  scope: string;
  details: string;
}
export interface Decision {
  id: string;
  choice: string;
  answers: Record<string, Array<string>>;
}
export interface Draft {
  notice: string;
  revision: number;
  text: string;
  referenceIds: Array<string>;
}
export interface ExecutionOptions {
  defaultApprovalMode: string;
  approvalModes: Array<ApprovalMode>;
}
export interface ExecutionSettings {
  model: string;
  effort: string;
  serviceTier: string;
  approvalMode: string;
}
export interface Item {
  requestId: string;
  turnKey: string;
  id: string;
  kind: string;
  text: string;
  status: string;
  details: string;
  activity: Activity | null;
  artifacts: Array<Artifact>;
  screen?: ScreenPresentation | null;
}
export interface ModelOption {
  imageInput: boolean | null;
  model: string;
  name: string;
  description: string;
  default: boolean;
  defaultEffort: string;
  efforts: Array<string>;
  serviceTiers: Array<ServiceTier>;
}
export interface NodeAddRequest {
  operationId?: string;
  label: string;
  join: string;
  sshDestination: string;
  expectedRevision: string;
}
export interface NodeAddResult {
  operationId?: string;
  outcome?: string;
  reason?: string;
  node: NodeInfo;
  joinInstructions: NodeJoinInstructions | null;
}
export interface NodeBroker {
  nodeId: string;
  reachable: boolean;
  automaticRoaming: boolean;
  reason: string;
  sourceRoutes?: Array<NodeCoordinatorSourceRoute>;
}
export interface NodeCatalog {
  revision: string;
  nodes: Array<NodeInfo>;
  selectedNodeId: string;
  activeBotNodeId: string;
  pairedRuntime: NodePairedRuntime | null;
  workerTarget: WorkTarget | null;
  broker: NodeBroker | null;
  pendingOperations: Array<NodeOperationRef>;
  pendingEnrollments?: Array<string>;
}
export interface NodeCoordinatorSelection {
  nodeId: string;
  expectedRevision: string;
  sourceRoutes?: Array<NodeCoordinatorSourceRoute> | null;
}
export interface NodeCoordinatorSourceRoute {
  sourceNodeId: string;
  sshDestination: string;
}
export interface NodeEditGuard {
  nodeId: string;
  backend: string;
  revision: string;
}
export interface NodeInfo {
  id: string;
  label: string;
  os: string;
  join: string;
  runtimes: Array<NodeRuntime>;
}
export interface NodeInstallationChange {
  action: string;
  version: string;
  expectedVersion: string;
}
export interface NodeInstallationState {
  installed: boolean;
  version: string;
  latestVersion: string;
}
export interface NodeJoinInstructions {
  nodeId: string;
  state: string;
  instructions: string;
}
export interface NodeManagementRequest {
  guard: NodeEditGuard;
  ref: NodeOperationRef;
  change: RuntimeConfigurationChange | null;
  installation: NodeInstallationChange | null;
}
export interface NodeOperationReceipt {
  ref: NodeOperationRef;
  outcome: string;
  revision: string;
  message: string;
}
export interface NodeOperationRef {
  nodeId: string;
  backend: string;
  operationId: string;
  requestDigest: string;
}
export interface NodePairedRuntime {
  nodeId: string;
  binding: string;
}
export interface NodeRoamingPlan {
  id: string;
  coordinatorNodeId: string;
  actions: Array<NodeRoamingPlanAction>;
  requiresConfirmation: boolean;
}
export interface NodeRoamingPlanAction {
  nodeId: string;
  label: string;
  action: string;
}
export interface NodeRoamingRequest {
  reviewedPlanId: string;
  allowPersistentExecution: boolean;
  id: string;
  expectedCatalogRevision: string;
}
export interface NodeRoamingState {
  available: boolean;
  operationId: string;
  outcome: string;
  enabled: boolean;
  coordinatorNodeId: string;
  activeBotNodeId: string;
  state: string;
  reason: string;
}
export interface NodeRoleCapability {
  role: string;
  eligible: boolean;
  reason: string;
}
export interface NodeRuntime {
  backend: string;
  version: string;
  authentication: string;
  health: string;
  roles: Array<NodeRoleCapability>;
}
export interface NodeRuntimeConfiguration {
  guard: NodeEditGuard;
  configuration: RuntimeConfiguration;
  conversation: WorkExecutionSettings | null;
  worker: WorkExecutionSettings | null;
  configurationAvailable: boolean;
  installerAvailable: boolean;
  executable?: NodeRuntimeExecutable | null;
  installation: NodeInstallationState | null;
  reviewedVersions: Array<string>;
}
export interface NodeRuntimeConnectionRef {
  nodeId: string;
  backend: string;
  operationId: string;
}
export interface NodeRuntimeExecutable {
  installed: boolean;
  version: string;
}
export interface ProductConnectionState {
  revision: number;
  pairing: ProductPairing;
  activeMode: string;
  state: string;
  issue: string;
  restartRequired: boolean;
}
export interface ProductPairing {
  mode: string;
  label: string;
  ssh: string;
  helper: string;
  endpoint: string;
  authFile: string;
  nodeId: string;
  botId: string;
}
export interface ProviderInfo {
  id: string;
  name: string;
  connectionKind: string;
  helpUrl: string;
  connectionHint: string;
}
export interface Question {
  id: string;
  title: string;
  secret: boolean;
  required: boolean;
  multiple: boolean;
  type: string;
  options: Array<Choice>;
}
export interface Receipt {
  id: string;
  outcome: string;
  message: string;
}
export interface Reference {
  id: string;
  name: string;
  description: string;
  kind: string;
}
export interface RemoteConfigurationRequest {
  id: string;
  binding: string;
  change: RuntimeConfigurationChange;
}
export interface RemoteExecutionRequest {
  id: string;
  binding: string;
  target: string;
  expectedRevision: string;
  selection: Selection;
}
export interface RemoteExecutionView {
  binding: string;
  conversationDefault: boolean;
  conversation: Selection;
  work?: Selection | null;
  revision: string;
  models: Array<ModelOption>;
}
export interface RemoteManagementResult {
  id: string;
  outcome: string;
  code: string;
  status?: Status | null;
  configuration?: RuntimeMutationResult | null;
}
export interface RemoteRuntimePending {
  id: string;
  kind: string;
  runtime?: RemoteRuntimeRequest | null;
}
export interface RemoteRuntimeRequest {
  id: string;
  binding: string;
  action: string;
  runtime: string;
  version: string;
  expectedVersion: string;
}
export interface RemoteRuntimeState {
  binding: string;
  label: string;
  available: boolean;
  capabilities: Capabilities;
  releases: Array<ReviewedRelease>;
  pending: Array<RemoteRuntimePending>;
}
export interface Review {
  id: string;
  status: string;
  action: string;
  rationale: string;
}
export interface ReviewedRelease {
  runtime: string;
  version: string;
}
export interface RuntimeAuthMethod {
  id: string;
  name: string;
  description: string;
  available: boolean;
  reason: string;
}
export interface RuntimeAuthorization {
  url: string;
  userCode: string;
  inputLabel: string;
  expiresAt: string;
  canSubmit: boolean;
}
export interface RuntimeCheck {
  saved: boolean;
  connected: boolean;
  message: string;
}
export interface RuntimeConfiguration {
  revision: string;
  main: WorkExecutionSettings;
  models: Array<ModelOption>;
  team: RuntimeTeam;
  connections: Array<RuntimeConnectionGroup>;
  oauthAvailable: boolean;
}
export interface RuntimeConfigurationChange {
  action: string;
  id: string;
  name: string;
  description: string;
  selection: WorkExecutionSettings;
  expectedRevision: string;
}
export interface RuntimeConnectChoice {
  id: string;
  name: string;
  description: string;
  custom: boolean;
}
export interface RuntimeConnectionCatalog {
  choices: Array<RuntimeConnectChoice>;
  unavailable: string;
}
export interface RuntimeConnectionGroup {
  id: string;
  name: string;
  kind: string;
  detail: string;
  models: Array<RuntimeConnectionModel>;
}
export interface RuntimeConnectionInput {
  settings: RuntimeSettings | null;
  kind: string;
  choice: string;
  command: string;
  baseUrl: string;
  model: string;
  apiKey: string;
  contextWindowTokens: number;
  maxOutputTokens: number;
  imageInput: boolean | null;
  reasoningLevels: Array<string>;
}
export interface RuntimeConnectionModel {
  id: string;
  name: string;
  uses: Array<string>;
  unavailable: boolean;
}
export interface RuntimeFlow {
  id: string;
  revision: string;
  sequence: number;
  stage: string;
  title: string;
  message: string;
  installation: RuntimeInstallation | null;
  authorization: RuntimeAuthorization | null;
  launchers: Array<RuntimeConnectChoice>;
  methods: Array<RuntimeAuthMethod>;
  models: Array<RuntimeFlowModel>;
}
export interface RuntimeFlowAction {
  id: string;
  revision: string;
  action: string;
  input: RuntimeFlowInput;
}
export interface RuntimeFlowInput {
  destination: string;
  launcher: string;
  method: string;
  code: string;
  model: string;
}
export interface RuntimeFlowModel {
  id: string;
  name: string;
  description: string;
}
export interface RuntimeInstallation {
  destination: string;
  source: string;
  platform: string;
  instructions: string;
  canInstall: boolean;
}
export interface RuntimeMutationResult {
  operationId: string;
  outcome: string;
  message: string;
}
export interface RuntimeRole {
  id: string;
  modelIds: Array<string>;
  description: string;
  system: boolean;
  custom: boolean;
  selection: WorkExecutionSettings;
  inherited: boolean;
  problem: string;
}
export interface RuntimeSettings {
  runtime: string;
  cliPath: string;
  caelisStore?: string;
}
export interface RuntimeStatus {
  latestVersion: string;
  updateState: string;
  installed: boolean;
  path: string;
  version: string;
  message: string;
}
export interface RuntimeTeam {
  available: boolean;
  reason: string;
  revision: string;
  roles: Array<RuntimeRole>;
  sets: Array<RuntimeTeamSet>;
  activeSet: string;
  models: Array<ModelOption>;
}
export interface RuntimeTeamSet {
  name: string;
  available: boolean;
  problem: string;
}
export interface ScreenImage {
  id: string;
  role: string;
  width: number;
  height: number;
}
export interface ScreenPresentation {
  application: string;
  images: Array<ScreenImage>;
}
export interface Selection {
  model: string;
  effort: string;
}
export interface ServiceTier {
  id: string;
  name: string;
  description: string;
}
export interface SetupChoice {
  value: string;
  label: string;
  noAuth: boolean;
  current: boolean;
}
export interface SetupOverview {
  active: string;
  pending: string;
  onboarding: boolean;
}
export interface SetupRequest {
  settings: RuntimeSettings;
  action: string;
  provider: string;
  baseUrl: string;
  model: string;
  apiKey: string;
}
export interface SetupState {
  serviceUpdateAvailable: boolean;
  serviceVersion: string;
  serviceState: string;
  selectedModel: string;
  settings: RuntimeSettings;
  installation: RuntimeStatus;
  state: string;
  message: string;
  models: Array<SetupChoice>;
  loginPending: boolean;
  accountType: string;
}
export interface Snapshot {
  maintenance?: string;
  scheduled: boolean;
  quiet: boolean;
  botStatus: string;
  hasEarlier: boolean;
  currentTurn: string;
  previewKey: string;
  previewDismissed: boolean;
  revision: number;
  connection: string;
  connectionIssue: string;
  phase: string;
  message: string;
  activity: Activity | null;
  canSend: boolean;
  canSteer: boolean;
  canInterrupt: boolean;
  items: Array<Item>;
  approvals: Array<Approval>;
  reviews: Array<Review>;
  references: Array<Reference>;
  loginPending: boolean;
  lastReceipt: Receipt;
}
export interface Status {
  runtime?: string;
  installed: boolean;
  version?: string;
  latestVersion?: string;
  updateState?: string;
  requestId?: string;
  outcome: string;
  message: string;
}
export interface Submission {
  id: string;
  text: string;
  fileIds: Array<string>;
  referenceIds: Array<string>;
}
export interface Task {
  target?: WorkTarget | null;
  id: string;
  title: string;
  workspace: string;
  status: string;
  outcome?: string;
  result?: string;
}
export interface TaskMessage {
  id: string;
  requestId: string;
  prompt: string;
}
export interface TaskPreview {
  target?: WorkTarget | null;
  targetLabel?: string;
  locked: boolean;
  provider?: string;
  id: string;
  prompt: string;
  status: string;
}
export interface TaskStart {
  target?: WorkTarget | null;
  requestId: string;
  title: string;
  prompt: string;
  workspace?: string;
}
export interface WorkExecutionSettings {
  model: string;
  effort: string;
  serviceTier: string;
}
export interface WorkTarget {
  nodeId: string;
  backend: string;
  role: string;
}
export interface WorkTargetInfo {
  target: WorkTarget;
  label: string;
  state: string;
}
export interface WorkerNodeConfig {
  transport?: string;
  id: string;
  label: string;
  ssh: string;
  helper: string;
  backend?: string;
  socket?: string;
  store: string;
  workspaceRoot: string;
}
export interface WorkerNodeFacts {
  os: string;
  arch: string;
  version: string;
}
export interface WorkerNodeSetup {
  revision: number;
  nodes: Array<WorkerNodeView>;
  issue: string;
}
export interface WorkerNodeView {
  config: WorkerNodeConfig;
  state: string;
  issue: string;
  facts: WorkerNodeFacts;
  connected: boolean;
}
