// Generated by go run ./cmd/contract-gen. Edit internal/backend/api/contract.go.
export interface Activity {
  kind: string;
  target: string;
}
export interface Approval {
  titleKey: string;
  noticeKey: string;
  taskTitle: string;
  owner?: string;
  sections: Array<ApprovalSection>;
  id: string;
  turnKey: string;
  title: string;
  action: string;
  target: string;
  description: string;
  details: string;
  status: string;
  resolution?: ApprovalResolution | null;
  choices: Array<Choice>;
  questions: Array<Question>;
  url: string;
}
export interface ApprovalMode {
  id: string;
  name: string;
  description: string;
  dangerous: boolean;
}
export interface ApprovalResolution {
  choiceId: string;
  outcome: string;
  scope?: string;
}
export interface ApprovalSection {
  titleKey: string;
  text: string;
}
export interface Artifact {
  id: string;
  name: string;
}
export interface AttachmentStorage {
  files: number;
  bytes: number;
  eligibleFiles: number;
  eligibleBytes: number;
  canClean: boolean;
  notice: string;
}
export interface BotInitialization {
  required: boolean;
  status: string;
  message: string;
}
export interface BotIntroduction {
  name: string;
  description: string;
}
export interface ChatUpdate {
  changed: boolean;
  snapshot: Snapshot;
}
export interface Choice {
  id: string;
  label: string;
  labelKey: string;
  scope: string;
  details: string;
}
export interface Decision {
  id: string;
  choice: string;
  answers: Record<string, Array<string>>;
}
export interface Draft {
  notice: string;
  cleanupPending?: boolean;
  rejectedCleanupPending?: boolean;
  pendingSend?: boolean;
  consumedFileIds?: Array<string>;
  revision: number;
  text: string;
  referenceIds: Array<string>;
}
export interface ExecutionOptions {
  defaultApprovalMode: string;
  approvalModes: Array<ApprovalMode>;
}
export interface ExecutionSettings {
  model: string;
  effort: string;
  serviceTier: string;
  approvalMode: string;
}
export interface Item {
  requestId: string;
  seenAt?: number;
  turnKey: string;
  id: string;
  kind: string;
  text: string;
  status: string;
  details: string;
  activity: Activity | null;
  artifacts: Array<Artifact>;
  screen?: ScreenPresentation | null;
  media?: MediaPresentation | null;
}
export interface LocalWorkerSettings {
  runtime: string;
  ready: boolean;
  work: WorkExecutionSettings;
  models: Array<ModelOption>;
  runtimeDefault: WorkExecutionSettings | null;
}
export interface Machine {
  id: string;
  name: string;
  address: string;
  port: number;
  user: string;
  authentication: string;
  sshConfig: boolean;
  privateKey: string;
  remember: boolean;
  state: string;
  issue: string;
  fingerprint: string;
  runtime: string;
  available: Array<string>;
  setup: SetupState;
  work: WorkExecutionSettings;
  models: Array<ModelOption>;
  runtimeDefault: WorkExecutionSettings | null;
  configuration?: RuntimeConfiguration | null;
  advancedIssue: string;
}
export interface MachineInput {
  id: string;
  name: string;
  address: string;
  port: number;
  user: string;
  authentication: string;
  sshConfig: boolean;
  privateKey: string;
  secret: string;
  remember: boolean;
  trustFingerprint: string;
}
export interface MachineModel {
  id: string;
  selection: WorkExecutionSettings;
}
export interface MachineTeamChange {
  id: string;
  change: RuntimeConfigurationChange;
}
export interface MediaImage {
  id: string;
  name: string;
  width: number;
  height: number;
  unavailable?: boolean;
}
export interface MediaPresentation {
  images: Array<MediaImage>;
  caption?: string;
}
export interface ModelOption {
  imageInput: boolean | null;
  model: string;
  name: string;
  description: string;
  default: boolean;
  defaultEffort: string;
  efforts: Array<string>;
  serviceTiers: Array<ServiceTier>;
}
export interface ProviderInfo {
  id: string;
  name: string;
  connectionKind: string;
  helpUrl: string;
  connectionHint: string;
}
export interface Question {
  id: string;
  title: string;
  secret: boolean;
  required: boolean;
  multiple: boolean;
  type: string;
  options: Array<Choice>;
}
export interface Receipt {
  id: string;
  outcome: string;
  message: string;
}
export interface Reference {
  id: string;
  name: string;
  description: string;
  kind: string;
}
export interface Review {
  id: string;
  turnKey: string;
  owner?: string;
  taskTitle?: string;
  status: string;
  action: string;
  rationale: string;
}
export interface RuntimeAuthMethod {
  id: string;
  name: string;
  description: string;
  available: boolean;
  reason: string;
}
export interface RuntimeAuthorization {
  url: string;
  userCode: string;
  inputLabel: string;
  expiresAt: string;
  canSubmit: boolean;
}
export interface RuntimeCheck {
  saved: boolean;
  connected: boolean;
  message: string;
}
export interface RuntimeConfiguration {
  revision: string;
  main: WorkExecutionSettings;
  models: Array<ModelOption>;
  team: RuntimeTeam;
  connections: Array<RuntimeConnectionGroup>;
  oauthAvailable: boolean;
}
export interface RuntimeConfigurationChange {
  action: string;
  id: string;
  name: string;
  description: string;
  selection: WorkExecutionSettings;
  expectedRevision: string;
}
export interface RuntimeConnectChoice {
  id: string;
  name: string;
  description: string;
  custom: boolean;
}
export interface RuntimeConnectionCatalog {
  choices: Array<RuntimeConnectChoice>;
  unavailable: string;
}
export interface RuntimeConnectionGroup {
  id: string;
  name: string;
  kind: string;
  detail: string;
  models: Array<RuntimeConnectionModel>;
}
export interface RuntimeConnectionInput {
  settings: RuntimeSettings | null;
  kind: string;
  choice: string;
  command: string;
  baseUrl: string;
  model: string;
  apiKey: string;
  contextWindowTokens: number;
  maxOutputTokens: number;
  imageInput: boolean | null;
  reasoningLevels: Array<string>;
}
export interface RuntimeConnectionModel {
  id: string;
  name: string;
  uses: Array<string>;
  unavailable: boolean;
}
export interface RuntimeFlow {
  id: string;
  revision: string;
  sequence: number;
  stage: string;
  title: string;
  message: string;
  installation: RuntimeInstallation | null;
  authorization: RuntimeAuthorization | null;
  launchers: Array<RuntimeConnectChoice>;
  methods: Array<RuntimeAuthMethod>;
  models: Array<RuntimeFlowModel>;
}
export interface RuntimeFlowAction {
  id: string;
  revision: string;
  action: string;
  input: RuntimeFlowInput;
}
export interface RuntimeFlowInput {
  destination: string;
  launcher: string;
  method: string;
  code: string;
  model: string;
}
export interface RuntimeFlowModel {
  id: string;
  name: string;
  description: string;
}
export interface RuntimeInstallation {
  destination: string;
  source: string;
  platform: string;
  instructions: string;
  canInstall: boolean;
}
export interface RuntimeMutationResult {
  operationId: string;
  outcome: string;
  message: string;
}
export interface RuntimeRole {
  id: string;
  modelIds: Array<string>;
  description: string;
  system: boolean;
  custom: boolean;
  selection: WorkExecutionSettings;
  inherited: boolean;
  problem: string;
}
export interface RuntimeSettings {
  runtime: string;
  cliPath: string;
  caelisStore?: string;
}
export interface RuntimeStatus {
  latestVersion: string;
  updateState: string;
  installed: boolean;
  path: string;
  version: string;
  message: string;
}
export interface RuntimeTeam {
  available: boolean;
  reason: string;
  revision: string;
  roles: Array<RuntimeRole>;
  sets: Array<RuntimeTeamSet>;
  activeSet: string;
  models: Array<ModelOption>;
}
export interface RuntimeTeamSet {
  name: string;
  available: boolean;
  problem: string;
}
export interface ScreenImage {
  id: string;
  role: string;
  width: number;
  height: number;
}
export interface ScreenPresentation {
  application: string;
  images: Array<ScreenImage>;
}
export interface ServiceTier {
  id: string;
  name: string;
  description: string;
}
export interface SetupChoice {
  value: string;
  label: string;
  noAuth: boolean;
  current: boolean;
}
export interface SetupOverview {
  active: string;
  hasRuntimeChoice: boolean;
  pending: string;
  onboarding: boolean;
}
export interface SetupRequest {
  settings: RuntimeSettings;
  action: string;
  provider: string;
  baseUrl: string;
  model: string;
  apiKey: string;
}
export interface SetupState {
  serviceUpdateAvailable: boolean;
  serviceVersion: string;
  serviceState: string;
  selectedModel: string;
  settings: RuntimeSettings;
  installation: RuntimeStatus;
  state: string;
  message: string;
  models: Array<SetupChoice>;
  loginPending: boolean;
  accountType: string;
}
export interface Snapshot {
  maintenance?: string;
  scheduled: boolean;
  quiet: boolean;
  botStatus: string;
  hasEarlier: boolean;
  currentTurn: string;
  previewKey: string;
  previewDismissed: boolean;
  revision: number;
  connection: string;
  connectionIssue: string;
  recoveryNoticeKey?: string;
  phase: string;
  message: string;
  activity: Activity | null;
  canSend: boolean;
  canSteer: boolean;
  canInterrupt: boolean;
  items: Array<Item>;
  approvals: Array<Approval>;
  reviews: Array<Review>;
  references: Array<Reference>;
  loginPending: boolean;
  lastReceipt: Receipt;
}
export interface Submission {
  id: string;
  text: string;
  fileIds: Array<string>;
  referenceIds: Array<string>;
}
export interface WorkExecutionSettings {
  model: string;
  effort: string;
  serviceTier: string;
}
