// Generated by go run ./cmd/contract-gen. Edit internal/backend/api/contract.go.
export interface Approval {
  id: string;
  title: string;
  action: string;
  target: string;
  description: string;
  details: string;
  status: string;
  choices: Array<Choice>;
  questions: Array<Question>;
  url: string;
}
export interface ApprovalMode {
  id: string;
  name: string;
  description: string;
  dangerous: boolean;
}
export interface Artifact {
  id: string;
  name: string;
}
export interface AttachmentStorage {
  files: number;
  bytes: number;
  eligibleFiles: number;
  eligibleBytes: number;
  canClean: boolean;
  notice: string;
}
export interface ChatUpdate {
  changed: boolean;
  snapshot: Snapshot;
}
export interface Choice {
  id: string;
  label: string;
  scope: string;
  details: string;
}
export interface Decision {
  id: string;
  choice: string;
  answers: Record<string, Array<string>>;
}
export interface Draft {
  notice: string;
  revision: number;
  text: string;
  referenceIds: Array<string>;
}
export interface ExecutionOptions {
  defaultApprovalMode: string;
  approvalModes: Array<ApprovalMode>;
}
export interface ExecutionSettings {
  model: string;
  effort: string;
  serviceTier: string;
  approvalMode: string;
}
export interface Item {
  turnKey: string;
  id: string;
  kind: string;
  text: string;
  status: string;
  details: string;
  artifacts: Array<Artifact>;
}
export interface ModelOption {
  model: string;
  name: string;
  description: string;
  default: boolean;
  defaultEffort: string;
  efforts: Array<string>;
  serviceTiers: Array<ServiceTier>;
}
export interface ProviderInfo {
  id: string;
  name: string;
  connectionKind: string;
  helpUrl: string;
  connectionHint: string;
}
export interface Question {
  id: string;
  title: string;
  secret: boolean;
  required: boolean;
  multiple: boolean;
  type: string;
  options: Array<Choice>;
}
export interface Receipt {
  id: string;
  outcome: string;
  message: string;
}
export interface Reference {
  id: string;
  name: string;
  description: string;
  kind: string;
}
export interface Review {
  id: string;
  status: string;
  action: string;
  rationale: string;
}
export interface RuntimeCheck {
  saved: boolean;
  connected: boolean;
  message: string;
}
export interface RuntimeSettings {
  runtime: string;
  cliPath: string;
}
export interface ServiceTier {
  id: string;
  name: string;
  description: string;
}
export interface Snapshot {
  botStatus: string;
  hasEarlier: boolean;
  currentTurn: string;
  previewKey: string;
  previewDismissed: boolean;
  revision: number;
  connection: string;
  connectionIssue: string;
  phase: string;
  message: string;
  canSend: boolean;
  canSteer: boolean;
  canInterrupt: boolean;
  items: Array<Item>;
  approvals: Array<Approval>;
  reviews: Array<Review>;
  references: Array<Reference>;
  loginPending: boolean;
  lastReceipt: Receipt;
}
export interface Submission {
  id: string;
  text: string;
  fileIds: Array<string>;
  referenceIds: Array<string>;
}
